langs = [
    {"name": "English"  , "code": "en_US"},
    {"name": "Français" , "code": "fr_FR"},
    {"name": "Deutsche" , "code": "de_DE"},
    {"name": "Español"  , "code": "es_ES"},
    {"name": "Polski"   , "code": "pl_PL"},
    {"name": "Português", "code": "pt_PT"},
    {"name": "Türk"     , "code": "tr_TR"},
    {"name": "Pусский"  , "code": "ru_RU"},
    {"name": "Pilipino" , "code": "fil_PH"}
]

currencies_fiat = [
    {"code": "AUD", "name": "Australian Dollar"         , "sym": "$"   },
    {"code": "CAD", "name": "Canadian Dollar"           , "sym": "$"   },
    {"code": "GBP", "name": "British Pound Sterling"    , "sym": "£"   },
    {"code": "NZD", "name": "New Zealand Dollar"        , "sym": "$"   },
    {"code": "USD", "name": "United States Dollar"      , "sym": "$"   },
    {"code": "ARS", "name": "Argentine Peso"            , "sym": "$"   },
    {"code": "MXN", "name": "Mexican Peso"              , "sym": "$"   },
    {"code": "VEF", "name": "Venezuelan Bolivar Fuerte" , "sym": "B$"  },
    {"code": "BRL", "name": "Brazil Real"               , "sym": "R$"  },
    {"code": "PHP", "name": "Philippine Peso"           , "sym": "₱"   },
    {"code": "RUB", "name": "Russian Ruble"             , "sym": "₽"   },
    {"code": "CHF", "name": "Swiss Franc"               , "sym": "CHF" },
    {"code": "PLN", "name": "Polish Zloty"              , "sym": "zł"  },
    {"code": "TRY", "name": "Turkish Lira"              , "sym": "₺"   },
    {"code": "EUR", "name": "Euro"                      , "sym": "€"   },
    {"code": "NGN", "name": "Nigerian Naira"            , "sym": "₦"   },
    {"code": "SGD", "name": "Singapore Dollar"          , "sym": "S$"  },
    {"code": "DKK", "name": "Danish Krone"              , "sym": "kr." },
    {"code": "MMK", "name": "Burmese Kyat"              , "sym": "K"   },
    {"code": "THB", "name": "Thai Baht"                 , "sym": "฿"   },
    {"code": "KRW", "name": "South Korean Won"          , "sym": "₩"   },
    {"code": "JPY", "name": "Japanese Yen"              , "sym": "¥"   },
    {"code": "CNY", "name": "Chinese Yuan"              , "sym": "¥"   },
    {"code": "INR", "name": "Indian Rupee"              , "sym": "₹"   },
    {"code": "SAR", "name": "Saudi Riyal"               , "sym": "﷼"   },
    {"code": "ZAR", "name": "South African Rand"        , "sym": "R"   },
    {"code": "BMD", "name": "Bermudian Dollar"          , "sym": "$"   },
    {"code": "CLP", "name": "Chilean Peso"              , "sym": "$"   },
    {"code": "HKD", "name": "Hong Kong Dollar"          , "sym": "元"  },
    {"code": "MYR", "name": "Malaysian Ringgit"         , "sym": "RM"  },
    {"code": "SEK", "name": "Swedish Krona"             , "sym": "kr"  },
    {"code": "UAH", "name": "Ukrainian Hryvnia"         , "sym": "₴"   },
    {"code": "XDR", "name": "IMF Special Drawing Rights", "sym": "SDR" },
    {"code": "CZK", "name": "Czech Koruna"              , "sym": "Kč"  },
    {"code": "HUF", "name": "Hungarian Forint"          , "sym": "Ft"  },
    {"code": "LKR", "name": "Sri Lankan Rupee"          , "sym": "ூ" },
    {"code": "PKR", "name": "Pakistani Rupee"           , "sym": "₨"   },
    {"code": "BDT", "name": "Bangladeshi Taka"          , "sym": "৳"   },
    {"code": "ILS", "name": "Israeli New Shekel"        , "sym": "₪"   },
    {"code": "NOK", "name": "Norwegian Krone"           , "sym": "kr"  },
    {"code": "VND", "name": "Vietnamese đồng"           , "sym": "₫/đ" },
    {"code": "IDR", "name": "Indonesian Rupiah"         , "sym": "Rp"  },
    {"code": "TWD", "name": "New Taiwan Dollar"         , "sym": "圓"  },
    {"code": "KWD", "name": "Kuwaiti Dinar"             , "sym": "د.ك" },
    {"code": "BHD", "name": "Bahraini Dinar"            , "sym": ".د.ب"}
]

currencies_crypto = [
    {"code": "BTC" , "name": "Bitcoin"                 , "sym": "₿"   },
    {"code": "BNB" , "name": "Binance Coin"            , "sym": "BNB" },
    {"code": "LINK", "name": "Chainlink"               , "sym": "LINK"},
    {"code": "ETH" , "name": "Ether"                   , "sym": "Ξ"   },
    {"code": "EOS" , "name": "EOS"                     , "sym": "ε"   },
    {"code": "DOT" , "name": "Polkadot"                , "sym": "DOT" },
    {"code": "BITS", "name": "Bits (100 satoshis)"     , "sym": "bits"},
    {"code": "XLM" , "name": "Lumens"                  , "sym": "XLM" },
    {"code": "BCH" , "name": "Bitcoin Cash"            , "sym": "Ƀ"   },
    {"code": "YFI" , "name": "Yearn.finance"           , "sym": "YFI" },
    {"code": "LTC" , "name": "Litecoin"                , "sym": "Ł"   },
    {"code": "SATS", "name": "Satoshi (0,00000001 BTC)", "sym": "sat" },
    {"code": "XRP" , "name": "XRP"                     , "sym": "✕"   }
]
