

langs = [
    {"name": "English"  , "code": "en_US"},
    {"name": "Français" , "code": "fr_FR"},
    {"name": "Deutsche" , "code": "de_DE"},
    {"name": "Español"  , "code": "es_ES"},
    {"name": "Polski"   , "code": "pl_PL"},
    {"name": "Português", "code": "pt_PT"},
    {"name": "Türk"     , "code": "tr_TR"},
    {"name": "Pусский"  , "code": "ru_RU"},
    {"name": "Pilipino" , "code": "fil_PH"}
]

currencies_fiat = [
    {"currency_code": "AUD", "currency_name": "Australian Dollar"         , "currency_sym": "$"   },
    {"currency_code": "CAD", "currency_name": "Canadian Dollar"           , "currency_sym": "$"   },
    {"currency_code": "GBP", "currency_name": "British Pound Sterling"    , "currency_sym": "£"   },
    {"currency_code": "NZD", "currency_name": "New Zealand Dollar"        , "currency_sym": "$"   },
    {"currency_code": "USD", "currency_name": "United States Dollar"      , "currency_sym": "$"   },
    {"currency_code": "ARS", "currency_name": "Argentine Peso"            , "currency_sym": "$"   },
    {"currency_code": "MXN", "currency_name": "Mexican Peso"              , "currency_sym": "$"   },
    {"currency_code": "VEF", "currency_name": "Venezuelan Bolivar Fuerte" , "currency_sym": "B$"  },
    {"currency_code": "BRL", "currency_name": "Brazil Real"               , "currency_sym": "R$"  },
    {"currency_code": "PHP", "currency_name": "Philippine Peso"           , "currency_sym": "₱"   },
    {"currency_code": "RUB", "currency_name": "Russian Ruble"             , "currency_sym": "₽"   },
    {"currency_code": "CHF", "currency_name": "Swiss Franc"               , "currency_sym": "CHF" },
    {"currency_code": "PLN", "currency_name": "Polish Zloty"              , "currency_sym": "zł"  },
    {"currency_code": "TRY", "currency_name": "Turkish Lira"              , "currency_sym": "₺"   },
    {"currency_code": "EUR", "currency_name": "Euro"                      , "currency_sym": "€"   },
    {"currency_code": "NGN", "currency_name": "Nigerian Naira"            , "currency_sym": "₦"   },
    {"currency_code": "SGD", "currency_name": "Singapore Dollar"          , "currency_sym": "S$"  },
    {"currency_code": "DKK", "currency_name": "Danish Krone"              , "currency_sym": "kr." },
    {"currency_code": "MMK", "currency_name": "Burmese Kyat"              , "currency_sym": "K"   },
    {"currency_code": "THB", "currency_name": "Thai Baht"                 , "currency_sym": "฿"   },
    {"currency_code": "KRW", "currency_name": "South Korean Won"          , "currency_sym": "₩"   },
    {"currency_code": "JPY", "currency_name": "Japanese Yen"              , "currency_sym": "¥"   },
    {"currency_code": "CNY", "currency_name": "Chinese Yuan"              , "currency_sym": "¥"   },
    {"currency_code": "INR", "currency_name": "Indian Rupee"              , "currency_sym": "₹"   },
    {"currency_code": "SAR", "currency_name": "Saudi Riyal"               , "currency_sym": "﷼"   },
    {"currency_code": "ZAR", "currency_name": "South African Rand"        , "currency_sym": "R"   },
    {"currency_code": "BMD", "currency_name": "Bermudian Dollar"          , "currency_sym": "$"   },
    {"currency_code": "CLP", "currency_name": "Chilean Peso"              , "currency_sym": "$"   },
    {"currency_code": "HKD", "currency_name": "Hong Kong Dollar"          , "currency_sym": "元"  },
    {"currency_code": "MYR", "currency_name": "Malaysian Ringgit"         , "currency_sym": "RM"  },
    {"currency_code": "SEK", "currency_name": "Swedish Krona"             , "currency_sym": "kr"  },
    {"currency_code": "UAH", "currency_name": "Ukrainian Hryvnia"         , "currency_sym": "₴"   },
    {"currency_code": "XDR", "currency_name": "IMF Special Drawing Rights", "currency_sym": "SDR" },
    {"currency_code": "CZK", "currency_name": "Czech Koruna"              , "currency_sym": "Kč"  },
    {"currency_code": "HUF", "currency_name": "Hungarian Forint"          , "currency_sym": "Ft"  },
    {"currency_code": "LKR", "currency_name": "Sri Lankan Rupee"          , "currency_sym": "ூ" },
    {"currency_code": "PKR", "currency_name": "Pakistani Rupee"           , "currency_sym": "₨"   },
    {"currency_code": "BDT", "currency_name": "Bangladeshi Taka"          , "currency_sym": "৳"   },
    {"currency_code": "ILS", "currency_name": "Israeli New Shekel"        , "currency_sym": "₪"   },
    {"currency_code": "NOK", "currency_name": "Norwegian Krone"           , "currency_sym": "kr"  },
    {"currency_code": "VND", "currency_name": "Vietnamese đồng"           , "currency_sym": "₫/đ" },
    {"currency_code": "IDR", "currency_name": "Indonesian Rupiah"         , "currency_sym": "Rp"  },
    {"currency_code": "TWD", "currency_name": "New Taiwan Dollar"         , "currency_sym": "圓"  },
    {"currency_code": "KWD", "currency_name": "Kuwaiti Dinar"             , "currency_sym": "د.ك" },
    {"currency_code": "BHD", "currency_name": "Bahraini Dinar"            , "currency_sym": ".د.ب"}
]

currencies_crypto = [
    {"currency_code": "BTC" , "currency_name": "Bitcoin"                 , "currency_sym": "₿"   },
    {"currency_code": "BNB" , "currency_name": "Binance Coin"            , "currency_sym": "BNB" },
    {"currency_code": "LINK", "currency_name": "Chainlink"               , "currency_sym": "LINK"},
    {"currency_code": "ETH" , "currency_name": "Ether"                   , "currency_sym": "Ξ"   },
    {"currency_code": "EOS" , "currency_name": "EOS"                     , "currency_sym": "ε"   },
    {"currency_code": "DOT" , "currency_name": "Polkadot"                , "currency_sym": "DOT" },
    {"currency_code": "BITS", "currency_name": "Bits (100 satoshis)"     , "currency_sym": "bits"},
    {"currency_code": "XLM" , "currency_name": "Lumens"                  , "currency_sym": "XLM" },
    {"currency_code": "BCH" , "currency_name": "Bitcoin Cash"            , "currency_sym": "Ƀ"   },
    {"currency_code": "YFI" , "currency_name": "Yearn.finance"           , "currency_sym": "YFI" },
    {"currency_code": "LTC" , "currency_name": "Litecoin"                , "currency_sym": "Ł"   },
    {"currency_code": "SATS", "currency_name": "Satoshi (0,00000001 BTC)", "currency_sym": "sat" },
    {"currency_code": "XRP" , "currency_name": "XRP"                     , "currency_sym": "✕"   }
]
